"""
Bootstrap Statistical Analysis - Calculate Bootstrap confidence intervals for metrics 
generated by 01-ROI_BenchMark_Main.py

Features:
1. Traverse all experiments in the results directory
2. Perform Bootstrap analysis on detailed results for each task (Linear-Probe, KNN, Proto)
3. Calculate 1000 Bootstrap 95% confidence intervals for each metric
4. Save results to JSON files

Output files:
- {experiment_name}/{task}/bootstrap_ci_results.json: Contains metrics and confidence intervals
"""

import os
import argparse
import json
import ast
import numpy as np
import pandas as pd
from typing import Dict, List, Tuple, Optional
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    roc_auc_score,
    average_precision_score,
    f1_score,
    precision_score,
    recall_score,
    cohen_kappa_score,
    brier_score_loss,
)
from sklearn.preprocessing import label_binarize
import warnings
warnings.filterwarnings('ignore')


def parse_probabilities(probs_str: str) -> np.ndarray:
    """Parse string format probabilities list"""
    try:
        probs_list = ast.literal_eval(probs_str)
        return np.array(probs_list, dtype=np.float32)
    except:
        probs_str = probs_str.strip('[]')
        probs_list = [float(x.strip()) for x in probs_str.split(',')]
        return np.array(probs_list, dtype=np.float32)


def calculate_ece_mce(y_true: np.ndarray, y_prob: np.ndarray, n_bins: int = 10) -> Tuple[float, float]:
    """
    Calculate Expected Calibration Error (ECE) and Maximum Calibration Error (MCE)
    
    Args:
        y_true: True labels (1D array, 0/1 indicating whether it matches the predicted class)
        y_prob: Predicted probabilities (1D array, probability for the true class)
        n_bins: Number of bins
    
    Returns:
        ECE, MCE
    """
    bin_boundaries = np.linspace(0, 1, n_bins + 1)
    bin_lowers = bin_boundaries[:-1]
    bin_uppers = bin_boundaries[1:]
    
    ece = 0.0
    mce = 0.0
    
    for bin_lower, bin_upper in zip(bin_lowers, bin_uppers):
        in_bin = (y_prob > bin_lower) & (y_prob <= bin_upper)
        prop_in_bin = in_bin.mean()
        
        if prop_in_bin > 0:
            accuracy_in_bin = y_true[in_bin].mean()
            avg_confidence_in_bin = y_prob[in_bin].mean()
            ece += np.abs(avg_confidence_in_bin - accuracy_in_bin) * prop_in_bin
            mce = max(mce, np.abs(avg_confidence_in_bin - accuracy_in_bin))
    
    return ece, mce


def calculate_metrics_single(y_true: np.ndarray, probs: np.ndarray) -> Dict[str, float]:
    """
    Calculate single-run metrics (for Bootstrap)
    
    Args:
        y_true: True labels
        probs: Predicted probabilities [n_samples, n_classes]
    
    Returns:
        Dictionary containing all metrics
    """
    y_pred = np.argmax(probs, axis=1)
    y_prob_true_class = probs[np.arange(len(y_true)), y_true]
    n_classes = probs.shape[1]
    
    # 1. ACC (Accuracy)
    acc = accuracy_score(y_true, y_pred)
    
    # 2. BACC (Balanced Accuracy)
    bacc = balanced_accuracy_score(y_true, y_pred)
    
    # 3. F1 Score
    f1_macro = f1_score(y_true, y_pred, average='macro', zero_division=0)
    f1_weighted = f1_score(y_true, y_pred, average='weighted', zero_division=0)
    f1_micro = f1_score(y_true, y_pred, average='micro', zero_division=0)
    
    # 4. Precision
    precision_macro = precision_score(y_true, y_pred, average='macro', zero_division=0)
    precision_weighted = precision_score(y_true, y_pred, average='weighted', zero_division=0)
    
    # 5. Recall
    recall_macro = recall_score(y_true, y_pred, average='macro', zero_division=0)
    recall_weighted = recall_score(y_true, y_pred, average='weighted', zero_division=0)
    
    # 6. AUC (ROC-AUC)
    try:
        if n_classes == 2:
            auc_macro = roc_auc_score(y_true, probs[:, 1])
            auc_weighted = auc_macro
            auc_micro = auc_macro
        else:
            auc_macro = roc_auc_score(y_true, probs, multi_class='ovr', average='macro')
            auc_weighted = roc_auc_score(y_true, probs, multi_class='ovr', average='weighted')
            auc_micro = roc_auc_score(y_true, probs, multi_class='ovr', average='micro')
    except Exception:
        auc_macro = auc_weighted = auc_micro = np.nan
    
    # 7. AUPRC (Average Precision)
    try:
        if n_classes == 2:
            auprc_macro = average_precision_score(y_true, probs[:, 1])
            auprc_weighted = auprc_macro
            auprc_micro = auprc_macro
        else:
            y_true_bin = label_binarize(y_true, classes=np.arange(n_classes))
            auprc_macro = average_precision_score(y_true_bin, probs, average='macro')
            auprc_weighted = average_precision_score(y_true_bin, probs, average='weighted')
            auprc_micro = average_precision_score(y_true_bin, probs, average='micro')
    except Exception:
        auprc_macro = auprc_weighted = auprc_micro = np.nan
    
    # 8. Brier Score
    y_true_onehot = np.zeros_like(probs)
    y_true_onehot[np.arange(len(y_true)), y_true] = 1
    brier_score = np.mean(np.sum((probs - y_true_onehot) ** 2, axis=1))
    
    # 9. ECE & MCE
    ece, mce = calculate_ece_mce(
        (y_pred == y_true).astype(int),
        y_prob_true_class, 
        n_bins=10
    )
    
    # 10. Kappa
    try:
        quadratic_kappa = cohen_kappa_score(y_true, y_pred, weights='quadratic')
        linear_kappa = cohen_kappa_score(y_true, y_pred, weights='linear')
    except Exception:
        quadratic_kappa = linear_kappa = np.nan
    
    metrics = {
        'acc': acc,
        'bacc': bacc,
        'macro_f1': f1_macro,
        'weighted_f1': f1_weighted,
        'micro_f1': f1_micro,
        'macro_precision': precision_macro,
        'weighted_precision': precision_weighted,
        'macro_recall': recall_macro,
        'weighted_recall': recall_weighted,
        'macro_auc': auc_macro,
        'weighted_auc': auc_weighted,
        'micro_auc': auc_micro,
        'macro_auprc': auprc_macro,
        'weighted_auprc': auprc_weighted,
        'micro_auprc': auprc_micro,
        'brier_score': brier_score,
        'ece': ece,
        'mce': mce,
        'quadratic_kappa': quadratic_kappa,
        'linear_kappa': linear_kappa,
    }
    
    return metrics


def bootstrap_ci(y_true: np.ndarray, probs: np.ndarray, 
                 n_bootstrap: int = 1000, 
                 random_state: int = 42,
                 ci_level: float = 0.95) -> Dict[str, Dict]:
    """
    Calculate confidence intervals for metrics using Bootstrap method
    
    Args:
        y_true: True labels
        probs: Predicted probabilities [n_samples, n_classes]
        n_bootstrap: Number of Bootstrap samples
        random_state: Random seed
        ci_level: Confidence level (default 0.95)
    
    Returns:
        Dictionary containing mean and confidence intervals for each metric
    """
    np.random.seed(random_state)
    n_samples = len(y_true)
    
    # Calculate original metrics
    original_metrics = calculate_metrics_single(y_true, probs)
    
    # Initialize Bootstrap results storage
    bootstrap_results = {key: [] for key in original_metrics.keys()}
    
    # Bootstrap sampling
    for _ in range(n_bootstrap):
        bootstrap_indices = np.random.choice(n_samples, size=n_samples, replace=True)
        y_true_boot = y_true[bootstrap_indices]
        probs_boot = probs[bootstrap_indices]
        
        # Ensure bootstrap sample contains all classes
        if len(np.unique(y_true_boot)) < 2:
            continue
            
        try:
            boot_metrics = calculate_metrics_single(y_true_boot, probs_boot)
            for key in bootstrap_results.keys():
                if not np.isnan(boot_metrics[key]):
                    bootstrap_results[key].append(boot_metrics[key])
        except Exception:
            continue
    
    # Calculate confidence intervals
    ci_lower = (1 - ci_level) / 2 * 100
    ci_upper = (1 + ci_level) / 2 * 100
    
    results = {}
    for key in original_metrics.keys():
        if len(bootstrap_results[key]) > 0:
            values = np.array(bootstrap_results[key])
            results[key] = {
                'value': float(original_metrics[key]) if not np.isnan(original_metrics[key]) else None,
                'ci_lower': float(np.percentile(values, ci_lower)),
                'ci_upper': float(np.percentile(values, ci_upper)),
                'std': float(np.std(values)),
                'n_valid_bootstrap': len(values)
            }
        else:
            results[key] = {
                'value': float(original_metrics[key]) if not np.isnan(original_metrics[key]) else None,
                'ci_lower': None,
                'ci_upper': None,
                'std': None,
                'n_valid_bootstrap': 0
            }
    
    return results


def process_detailed_results(csv_path: str, n_bootstrap: int = 1000, random_state: int = 42) -> Dict:
    """
    Process detailed results file and calculate Bootstrap CI
    
    Args:
        csv_path: Path to detailed results CSV file
        n_bootstrap: Number of Bootstrap samples
        random_state: Random seed
    
    Returns:
        Dictionary containing Bootstrap CI results
    """
    df = pd.read_csv(csv_path)
    
    # Parse probabilities column
    probs_list = []
    for probs_str in df['probabilities']:
        probs_array = parse_probabilities(probs_str)
        probs_list.append(probs_array)
    probs = np.array(probs_list)
    
    # Get true labels
    y_true = df['true_label'].values.astype(np.int64)
    
    n_samples = len(y_true)
    n_classes = probs.shape[1]
    
    print(f"    Samples: {n_samples}, Classes: {n_classes}")
    print(f"    Running {n_bootstrap} Bootstrap samples...")
    
    # Calculate Bootstrap CI
    ci_results = bootstrap_ci(y_true, probs, n_bootstrap=n_bootstrap, random_state=random_state)
    
    # Add metadata
    results = {
        'n_samples': n_samples,
        'n_classes': n_classes,
        'n_bootstrap': n_bootstrap,
        'ci_level': 0.95,
        'metrics': ci_results
    }
    
    return results


def find_all_experiments(results_dir: str) -> List[str]:
    """
    Find all experiment directories in results directory
    
    Args:
        results_dir: Root results directory
    
    Returns:
        List of experiment directories
    """
    experiments = []
    if not os.path.exists(results_dir):
        print(f"Results directory does not exist: {results_dir}")
        return experiments
    
    for item in os.listdir(results_dir):
        item_path = os.path.join(results_dir, item)
        if os.path.isdir(item_path):
            # Check if it contains task subdirectories
            has_task = False
            for task in ['Linear-Probe', 'KNN', 'Proto']:
                task_path = os.path.join(item_path, task)
                if os.path.isdir(task_path):
                    has_task = True
                    break
            if has_task:
                experiments.append(item)
    
    return sorted(experiments)


def find_all_tasks(experiment_dir: str) -> List[str]:
    """
    Find all tasks in experiment directory
    
    Args:
        experiment_dir: Path to experiment directory
    
    Returns:
        List of tasks
    """
    tasks = []
    # Regular tasks that have detailed_results.csv files
    task_names = ['Linear-Probe', 'KNN', 'Proto']
    
    for task in task_names:
        task_path = os.path.join(experiment_dir, task)
        if os.path.isdir(task_path):
            # Check if detailed results file exists
            detailed_csv = os.path.join(task_path, f'{task}_detailed_results.csv')
            if os.path.exists(detailed_csv):
                tasks.append(task)
                print(f"    Found task: {task} (has detailed_results.csv)")
            else:
                print(f"    Skipping task: {task} (no detailed_results.csv found)")
    
    return tasks


def process_experiment(experiment_dir: str, experiment_name: str, 
                       n_bootstrap: int = 1000, random_state: int = 42) -> Dict:
    """
    Process all tasks for a single experiment
    
    Args:
        experiment_dir: Path to experiment directory
        experiment_name: Experiment name
        n_bootstrap: Number of Bootstrap samples
        random_state: Random seed
    
    Returns:
        Experiment results dictionary
    """
    experiment_results = {
        'experiment_name': experiment_name,
        'tasks': {}
    }
    
    tasks = find_all_tasks(experiment_dir)
    
    for task in tasks:
        task_path = os.path.join(experiment_dir, task)
        
        # Regular task (Linear-Probe, KNN, Proto)
        detailed_csv = os.path.join(task_path, f'{task}_detailed_results.csv')
        output_json = os.path.join(task_path, f'{task}_bootstrap_ci.json')
        
        if os.path.exists(detailed_csv):
            # Skip if output file already exists
            if os.path.exists(output_json):
                    print(f"  Skipping: {task} (output file already exists)")
                    try:
                        # Load existing results
                        with open(output_json, 'r', encoding='utf-8') as f:
                            results = json.load(f)
                        experiment_results['tasks'][task] = results
                        print(f"    ✓ Loaded existing results from: {output_json}")
                    except Exception as e:
                        print(f"    ⚠ Failed to load existing file, will reprocess: {str(e)}")
                        # If loading fails, continue to process
                        try:
                            results = process_detailed_results(detailed_csv, n_bootstrap, random_state)
                            experiment_results['tasks'][task] = results
                            
                            # Save result
                            with open(output_json, 'w', encoding='utf-8') as f:
                                json.dump(results, f, indent=2, ensure_ascii=False)
                            print(f"    ✓ Saved: {output_json}")
                        except Exception as e2:
                            print(f"    ✗ Failed: {str(e2)}")
                            import traceback
                            traceback.print_exc()
            else:
                print(f"  Processing: {task}")
                try:
                    results = process_detailed_results(detailed_csv, n_bootstrap, random_state)
                    experiment_results['tasks'][task] = results
                    
                    # Save result
                    with open(output_json, 'w', encoding='utf-8') as f:
                        json.dump(results, f, indent=2, ensure_ascii=False)
                    print(f"    ✓ Saved: {output_json}")
                except Exception as e:
                    print(f"    ✗ Failed: {str(e)}")
                    import traceback
                    traceback.print_exc()
        else:
            print(f"  Warning: {task} directory exists but detailed_results.csv not found")
    
    return experiment_results


def main(args):
    """Main function"""
    results_dir = args.results_dir
    n_bootstrap = args.n_bootstrap
    random_state = args.random_state
    
    print("=" * 80)
    print("Bootstrap Statistical Analysis")
    print("=" * 80)
    print(f"Results directory: {results_dir}")
    print(f"Bootstrap iterations: {n_bootstrap}")
    print(f"Random seed: {random_state}")
    print("=" * 80)
    
    # Find all experiments
    experiments = find_all_experiments(results_dir)
    
    if len(experiments) == 0:
        print("No experiment directories found")
        return
    
    print(f"Found {len(experiments)} experiments:")
    for exp in experiments:
        print(f"  - {exp}")
    print("=" * 80)
    
    # Process each experiment
    all_results = {}
    for idx, experiment_name in enumerate(experiments, 1):
        experiment_dir = os.path.join(results_dir, experiment_name)
        print(f"\n[{idx}/{len(experiments)}] Processing experiment: {experiment_name}")
        print("-" * 40)
        
        experiment_results = process_experiment(
            experiment_dir, 
            experiment_name, 
            n_bootstrap, 
            random_state
        )
        all_results[experiment_name] = experiment_results
    
    # Save summary results
    summary_output = os.path.join(results_dir, 'bootstrap_ci_summary.json')
    with open(summary_output, 'w', encoding='utf-8') as f:
        json.dump(all_results, f, indent=2, ensure_ascii=False)
    
    print("\n" + "=" * 80)
    print(f"Summary results saved to: {summary_output}")
    print("=" * 80)
    
    # Print summary statistics
    print("\nSummary statistics:")
    for exp_name, exp_data in all_results.items():
        print(f"\n{exp_name}:")
        for task_name, task_data in exp_data.get('tasks', {}).items():
            # Regular task (Linear-Probe, KNN, Proto)
            if isinstance(task_data, dict) and 'metrics' in task_data:
                metrics = task_data['metrics']
                acc = metrics.get('acc', {})
                auc = metrics.get('macro_auc', {})
                print(f"  {task_name}:")
                if acc.get('value') is not None:
                    print(f"    ACC: {acc['value']:.4f} [{acc.get('ci_lower', 0):.4f}, {acc.get('ci_upper', 0):.4f}]")
                if auc.get('value') is not None:
                    print(f"    AUC: {auc['value']:.4f} [{auc.get('ci_lower', 0):.4f}, {auc.get('ci_upper', 0):.4f}]")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Bootstrap Statistical Analysis for ROI Benchmark Results')
    parser.add_argument('--results_dir', type=str, 
                        default='/ai-data/lxt166/Patho3DMatrix/results',
                        help='Path to results directory')
    parser.add_argument('--n_bootstrap', type=int, default=1000,
                        help='Number of Bootstrap samples')
    parser.add_argument('--random_state', type=int, default=42,
                        help='Random seed')
    
    args = parser.parse_args()
    main(args)

